
export const SIGNUP = "SIGNUP"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const GET = "GET"
export const ADD_PRODUCT = "ADD_PRODUCT"    
export const SINGLE_PRODUCT = "SINGLE_PRODUCT"    
export const ADD_CART = "ADD_CART"
export const GET_CART = "GET_CART"
export const DELET_CART = "DELET_CART"